services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - export:/usr/src/paperless/export
      - hooks:/usr/src/paperless/scripts
      - trash:/usr/src/paperless/trash
      - type: bind
        source: /mnt/media/Paperless/consume
        target: /usr/src/paperless/consume
      - type: bind
        source: /mnt/media/Paperless
        target: /usr/src/paperless/media
    env_file: .env
    environment:
      PAPERLESS_REDIS: $REDIS_URL
      PAPERLESS_DBHOST: db-paperless
      PAPERLESS_DBPASS: $PG_PW
      PAPERLESS_DBUSER: $PG_USER
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_ADMIN_USER: $ADMIN
      PAPERLESS_ADMIN_MAIL: $ADMIN_EMAIL
      PAPERLESS_ADMIN_PASSWORD: $ADMIN_PW
      PAPERLESS_EMAIL_HOST: $SMTP_HOST
      PAPERLESS_EMAIL_PORT: $SMTP_PORT
      PAPERLESS_EMAIL_HOST_USER: $SMTP_USER
      PAPERLESS_EMAIL_FROM: $FROM
      PAPERLESS_EMAIL_HOST_PASSWORD: $SMTP_KEY
      PAPERLESS_URL: $DOMAIN
      PAPERLESS_USE_X_FORWARD_HOST: true
      PAPERLESS_USE_X_FORWARD_PORT: true
      PAPERLESS_PROXY_SSL_HEADER: '["HTTP_X_FORWARDED_PROTO", "https"]'
      PAPERLESS_ENABLE_UPDATE_CHECK: true
      PAPERLESS_OCR_LANGUAGES: deu eng fra
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_FILENAME_FORMAT: '{created_year}/{correspondent}/{title}'
      # QR Code Scanner
      PAPERLESS_CONSUMER_ENABLE_BARCODES: true
      PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: true
      PAPERLESS_CONSUMER_BARCODE_SCANNER: ZXING
      # Polling rate
      PAPERLESS_CONSUMER_POLLING: 60
      

    depends_on:
      - gotenberg
      - tika
      - db-paperless
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  gotenberg:
    image: docker.io/gotenberg/gotenberg:latest
    container_name: gotenberg
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    container_name: tika
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
  db-paperless:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    container_name: db-paperless
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PW

volumes:
  data:
  export:
  hooks:
  trash:
  pgdata:
