services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    hostname: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
        - config:/config
        - data:/data
    ports:
      - 8888:443
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  config:
  data:


#For running occ use the following command: docker exec -it nextcloud occ maintenance:repair --include-expensive
