services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      WATCHTOWER_CLEANUP: "true"
      # WATCHTOWER_POLL_INTERVAL: "86400"
      WATCHTOWER_POLL_INTERVAL: "3600"
      WATCHTOWER_LABEL_ENABLE: "true"
      # WATCHTOWER_DEBUG: "true"
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      # WATCHTOWER_NOTIFICATIONS_LEVEL: "debug"
      WATCHTOWER_NOTIFICATION_URL: smtp://${SMTP_USER}:${SMTP_PASSWORD}@${SMTP_SERVER}:${SMTP_PORT}/?to=${SMTP_TO}&from=${SMTP_FROM}&encryption=ExplicitTLS

      # WATCHTOWER_NOTIFICATIONS: "email"
      # WATCHTOWER_NOTIFICATION_EMAIL_FROM: ${SMTP_FROM}
      # WATCHTOWER_NOTIFICATION_EMAIL_TO: ${SMTP_TO}
      # WATCHTOWER_NOTIFICATION_EMAIL_SERVER: ${SMTP_SERVER}
      # WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: ${SMTP_PORT}
      # WATCHTOWER_NOTIFICATION_EMAIL_USERNAME: ${SMTP_USER}
      # WATCHTOWER_NOTIFICATION_EMAIL_PASSWORD: ${SMTP_PASSWORD}
      TZ: Europe/Berlin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

# WATCHTOWER_NOTIFICATION_URL=smtp://${SMTP_USER}:${SMTP_PASSWORD}@/?to=${SMTP_TOM}&from=${SMTP_FROM}&encryption=ExplicitTLS
