services:
  collabora:
    image: collabora/code
    container_name: collabora
    hostname: collabora
    restart: always
    ports:
      - 9980:9980
      - 9994:9980
      - 9993:9980
    environment:
      aliasgroup1: $NC_HOST
      aliasgroup2: https://192.168.31.214:8888
      TZ: Europe/Berlin
      dictionaries: de_DE
    cap_add:
      - MKNOD
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
