services:
  adguardHome:
    image: adguard/adguardhome:latest
    container_name: adguardHome
    hostname: adguardHome
    restart: always
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
    - adguardWork:/opt/adguardhome/work
    - adguardConf:/opt/adguardhome/conf

volumes:
  adguardWork:
  adguardConf:
