services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - jellyConfig:/config
      - jellyCache:/cache
      - type: bind
        source: /mnt/media
        target: /media
        read_only: true
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  jellyConfig:
  jellyCache: