services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 9443:9443
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


volumes:
  portainer:



