# services:
#   postgres:
#     image: postgres:16
#     restart: always
#     container_name: postgres
#     hostname: postgres
#     environment:
#       POSTGRES_PASSWORD: ${PG_PASSWORD}
#       POSTGRES_USER: fanto
#       POSTGRES_DB: nextcloud
#       PGDATA: /var/lib/postgresql/data/pgdata
#     volumes:
#       - postgres:/var/lib/postgresql/data
#     ports:
#       - 5432:5432


#   adminer:
#     image: adminer
#     container_name: adminer
#     restart: always
#     ports:
#       - 8078:8080

# volumes:
#   postgres:
