services:
    redis:
      image: redis
      container_name: redis
      hostname: redis
      ports: 
        - 6379:6379
      restart: always
      volumes:
        - redis:/data

volumes:
  redis: